### PR TITLE
WIP: Tests/coverage

### PR DESCRIPTION
**Pull request by fntlnz**
The aim of this PR is to test what we have in order to have a solid foundation on which build up kappa

### CODE REVIEW

**Comment by atosatto** [comment]
So good to see @fntlnz working on this. I'm definitively bad at writing tests before writing real code. :sweat_smile:

**Comment by atosatto** [comment]
@fntlnz is this still WIP?

**Comment by fntlnz** [comment]
@atosatto Yes

**Comment by fntlnz** [comment]
This can be considered closed @atosatto @jnardiello - please express your opinions so we can merge

**Comment by atosatto** [comment]
So good @fntlnz. Thank you very much for this! 😄 

LGTM

**Comment by jnardiello** [comment]
LGMT

**Comment by atosatto** [comment]
LGTM

**Pull request merged**
