### PR TITLE
Added Docker host in Docker Backend Config

### PR DESCRIPTION
**Pull request by fntlnz**

### CODE REVIEW

**Comment by atosatto** [comment]
LGTM

PS: Super Lore! :smile:

**Comment by fntlnz** [comment]
@jnardiello waiting for you

**Comment by atosatto** [comment]
Since he asked for it, I've removed @jnardiello from the MAINTAINERS file 😢.
@fntlnz rebase your PR and let's get this merged! 😄

**Comment by fntlnz** [comment]
@atosatto sad but true

**Pull request merged**
